sonar.projectKey=xdubois-57_secondstay
sonar.organization=xdubois-57
sonar.projectName=SecondStay

sonar.sources=src,public/assets/js,templates,translations,migrations
sonar.tests=tests
sonar.exclusions=public/assets/vendor/**,vendor/**,node_modules/**,build/**,coverage/**
sonar.test.exclusions=vendor/**,node_modules/**

sonar.sourceEncoding=UTF-8

sonar.php.coverage.reportPaths=build/coverage/clover.xml
sonar.php.tests.reportPath=build/reports/phpunit-junit.xml
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.qualitygate.wait=true
